# Generated by Django 3.1 on 2020-10-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_type', models.CharField(max_length=20)),
                ('species_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=10)),
                ('pet_name', models.CharField(max_length=64)),
                ('pet_type', models.CharField(max_length=20)),
                ('pet_born_day', models.CharField(max_length=2)),
                ('pet_born_month', models.CharField(max_length=2)),
                ('pet_born_year', models.CharField(max_length=4)),
                ('pet_species', models.ManyToManyField(blank=True, related_name='pets', to='user.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=64)),
                ('owner_surname', models.CharField(max_length=64)),
                ('owner_phone', models.CharField(max_length=10)),
                ('owner_pet', models.ManyToManyField(blank=True, related_name='owners', to='user.Pet')),
            ],
        ),
    ]
