# Generated by Django 3.1 on 2020-10-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=10)),
                ('comment_detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(default='0000000001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_eye_color',
            field=models.CharField(default='brown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_hair_color',
            field=models.CharField(default='brown', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.CharField(max_length=10)),
                ('forum_topic', models.CharField(max_length=100)),
                ('forum_user', models.CharField(max_length=64)),
                ('forum_comment', models.ManyToManyField(blank=True, related_name='comments', to='user.Comment')),
            ],
        ),
    ]
