# Generated by Django 3.1 on 2020-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201026_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_profile',
            field=models.CharField(default='0', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_profile',
            field=models.CharField(default='0', max_length=300),
            preserve_default=False,
        ),
    ]
