# Generated by Django 3.1 on 2020-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201027_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_email',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
    ]
