# Generated by Django 3.1 on 2020-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201102_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_id',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
