# Generated by Django 3.1 on 2020-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pet_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='forum_comment',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_gallery',
            field=models.CharField(default='none', max_length=100000),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_username',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner_id',
            field=models.CharField(default='0000000', max_length=64),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_eye_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_hair_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
