# Generated by Django 3.1 on 2020-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201119_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=10)),
                ('comment_detail', models.CharField(max_length=10000)),
                ('comment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner_id',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
