# Generated by Django 3.1 on 2020-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201119_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
